### ISSUE TITLE
Chapter using PNAD (or other major survey)

### ISSUE THREAD

**Issue by guilhermejacob** [guilhermejacob/context#6]
This would show more about the package capacity to work on large surveys.
And I can work on optimizing some code also).
Should we?

**Comment by ajdamico** [comment]
@DjalmaPessoa and i talked about this last week.  at first i thought we should obviously do this, but he convinced me otherwise..  the examples might be too big for the scope of this book.  my goal for next year is to convert asdfree.com to a book, modeled on this one.  the examples could go there.  on the topic, here's what we have:

https://github.com/ajdamico/asdfree/blob/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/test_pnad2011.R

https://github.com/ajdamico/asdfree/blob/29bbf9690bb82f2eef74331e61112dfeeb2b7128/Current%20Population%20Survey/income%20concentration%20examples.R

https://github.com/ajdamico/asdfree/blob/29bbf9690bb82f2eef74331e61112dfeeb2b7128/Survey%20of%20Consumer%20Finances/income%20concentration%20examples.R

**Comment by ajdamico** [comment]
i see `convey` being showcased as much as possible as a part of https://github.com/ajdamico/asdfree/issues/176

**Comment by ajdamico** [comment]
closing because i think this belongs here instead?  https://github.com/ajdamico/asdfree/issues/176  reopen if you want to discuss more, thanks

**Comment by ajdamico** [comment]
@guilhermejacob @DjalmaPessoa so you can see how i am pushing `convey` into widespread usage:  https://ajdamico.github.io/asdfreebook/

chapter 4.3, 5.3, and 6.3, which each showcase convey, are all automatically generated from the dataset-specific metadata here:

https://github.com/ajdamico/asdfreebook/blob/master/metadata/pnad.txt#L38-L40
https://github.com/ajdamico/asdfreebook/blob/master/metadata/scf.txt#L35-L37
https://github.com/ajdamico/asdfreebook/blob/master/metadata/yrbss.txt#L40-L42

the book auto-populates (described https://github.com/ajdamico/asdfree/issues/176) which makes it easy for me to include `convey` snippets for every single microdata file on asdfree.com that includes an income variable.

all of this is still very rough

**Comment by DjalmaPessoa** [comment]
don't forget to use the subset design:
svygini(~v4720, subset( pnad_des, is.na(v4720)==FALSE & v4720!=0 &  v8005>=15)

**Comment by ajdamico** [comment]
yep..still working on the template
